spring:
  main:
    web-application-type: none
  jackson:
    date-format: yyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  lifecycle:
    timeout-per-shutdown-phase: "20s"
  datasource:
    url: jdbc:mysql://replica-db5:3306/mytest2?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 666666
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 10000
      minimum-idle: 10
      maximum-pool-size: 20
      idle-timeout: 30000
      max-lifetime: 60000

rocketmq:
  name-server: 192.168.88.123:9876;
  consumer:
    group: your_consumer_group8
    subscribe: mytest2